version: '3'
services:
  database:
    image: influxdb
      environment:
        NFLUXDB_DB: sensordata
        INFLUXDB_USER: telegraf
        INFLUXDB_USER_PASSWORD: telegraf
      volumes:
        - /home/ubuntu/PI4Server/influxdb/db:/var/lib/influxdb
        - /home/ubuntu/PI4Server/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      ports:
        - "8086:8086"

  frontend:
    image: grafana/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - "3000:3000"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/ubuntu/PI4Server/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mqttutil:
    image: telegraf
    volumes:
      - /home/pi/PI4Server/telegraf/:/etc/telegraf:ro
