version: '3'
services:

  pihole:
    image: pihole/pihole:latest
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - /home/ubuntu/PI4Server/pihole/etc-pihole:/etc/pihole
      - /home/ubuntu/PI4Server/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - target: 53
        published: 53
        mode: host
      - target: 67
        published: 67
        mode: host
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    environment:
      - TZ='Europe/Oslo'
      - WEBPASSWORD="thats_just_personal_you_know"
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all
    dns:
      - 127.0.0.1
      - 1.1.1.1
