version: '3.3'

services:
  app:
    image: swarmpit/swarmpit:1.9
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 8080
        published: 888
        mode: host

    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
      placement:
        constraints:
          - node.role == manager
  db:
    image: treehouses/couchdb:2.1.1
    volumes:
      - /home/ubuntu/PI4Server/swarmpit/db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  influxdb:
    image: influxdb:1.7
    volumes:
      - /home/ubuntu/PI4Server/swarmpit/influxdb-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
