version: "3.8"
services:
  shepherd:
    image: mazzolino/shepherd
    logging:
      driver: "splunk"
      options:
        splunk-token: 4189e578-d38c-482b-a7d4-40cefa1760c4
        splunk-url: https://192.168.50.3:8088
        splunk-format: json
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}/{{.Name}}"
    networks:
      - notification
    environment:
      FILTER_SERVICES: "label=tiny.angry.kitten.autodeploy"
      WITH_REGISTRY_AUTH: "true"
      SLEEP_TIME: "60m"
      IMAGE_AUTOCLEAN_LIMIT: "5"
      VERBOSE: "true"
      TZ: "Europe/Oslo"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
      placement:
        constraints:
        - node.role == manager
networks:
  notification:
