version: "3.8"
services:
  shepherd:
    image: mazzolino/shepherd
    networks:
      - notification
    environment:
      FILTER_SERVICES: "label=tiny.angry.kitten.autodeploy"
      APPRISE_SIDECAR_URL: "apprise:8000"
      VERBOSE: "true"
      TZ: "Europe/Oslo"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
      placement:
        constraints:
        - node.role == manager
  apprise:
    image: mazzolino/apprise-microservice:0.1
    ports:
      - target: 5000
        published: 5000
        mode: host
      - target: 8000
        published: 8000
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
      placement:
        constraints:
        - node.role == worker
    environment:
      NOTIFICATION_URLS: ""
      DEBUG: 1
    networks:
      - notification
networks:
  notification:
