version: "3.8"
services:
  shepherd:
    image: mazzolino/shepherd
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    networks:
      - notification
    environment:
      FILTER_SERVICES: "label=tiny.angry.kitten.autodeploy"
      WITH_REGISTRY_AUTH: "true"
      SLEEP_TIME: "60m"
      IMAGE_AUTOCLEAN_LIMIT: "5"
      VERBOSE: "true"
      TZ: "Europe/Oslo"
    volumes:
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: /root/.docker/config.json
        target: /root/.docker/config.json
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
      placement:
        constraints:
        - node.role == manager
networks:
  notification:
