version: "3"
services:
  shepherd:
    build: .
    image: mazzolino/shepherd
    networks:
      - notification
    environment:
      FILTER_SERVICES: "label=tiny.angry.kitten.autodeploy"
      APPRISE_SIDECAR_URL: "apprise:8000"
      VERBOSE: "true"
      TZ: "Europe/Oslo"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - tiny.angry.kitten.autodeploy
      placement:
        constraints:
        - node.role == manager
  apprise:
    image: mazzolino/apprise-microservice:0.1
    ports:
      - target: 5000
        published: 5000
        mode: host

    deploy:
      labels:
        - tiny.angry.kitten.autodeploy
      placement:
        constraints:
        - node.role == worker
    environment:
      NOTIFICATION_URLS: ""
    networks:
      - notification
networks:
  notification:
