version: "3.8"
services:
  pihole:
    image: pihole/pihole:latest
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    volumes:
      - piholevolume:/etc/pihole #"/home/ubuntu/PI4Server/pihole/etc-pihole:/etc/pihole"
      - dnsvolume:/etc/dnsmasq.d #"/home/ubuntu/PI4Server/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - target: 53
        published: 53
        mode: host
      - target: 67
        published: 67
        mode: host
      - target: 80
        published: 8081
        mode: host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      placement:
        constraints:
          - node.role == worker
    environment:
      - TZ='Europe/Oslo'
      - WEBPASSWORD="maybeputapasswordhere"
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all
    dns:
      - 127.0.0.1
      - 1.1.1.1

volumes:
   dnsvolume:
    external: true
   piholevolume:
     external: true
