version: "3.8"
services:

  pihole:
    image: pihole/pihole:latest
    volumes:
      - piholevolume::/etc/pihole #"/home/ubuntu/PI4Server/pihole/etc-pihole:/etc/pihole"
      - dnsvolume:/etc/dnsmasq.d #"/home/ubuntu/PI4Server/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    ports:
      - target: 53
        published: 53
        mode: host
      - target: 67
        published: 67
        mode: host
      - target: 80
        published: 8081
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == worker
    volumes:
      piholevolume:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.0.0.96,rw
          device: ":/home/ubuntu/PI4Server/pihole/etc-pihole"
      dnsvolume:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.0.0.96,rw
          device: ":/home/ubuntu/PI4Server/pihole/etc-dnsmasq.d"
    environment:
      - TZ='Europe/Oslo'
      - WEBPASSWORD="maybeputapasswordhere"
      - FTL_CMD=debug
      - DNSMASQ_LISTENING=all
    dns:
      - 127.0.0.1
      - 1.1.1.1
