version: "3.7"

networks:
  proxy:
    external: true

  consul:
    image: consul:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - target: 8500
        published: 8500
        mode: host
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`consul.localhost`)"
        - "traefik.http.services.consul.loadbalancer.server.port=8500"

volumes:
  letsencrypt:
