version: '3.8'
services:
    grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    ports:
      - target: 3000
        published: 3000

  mqtt:
    image: eclipse-mosquitto
    ports:
      - target: 1883
        published: 1883
      - target: 9001
        published: 9001
    volumes:
      - /home/ubuntu/PI4Server/mqtt_microservices/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  telegraf:
    image: telegraf
    volumes:
      - /home/ubuntu/PI4Server/mqtt_microservices/telegraf/:/etc/telegraf

  influx:
    image: influxdb
    ports:
      - target: 8086
        published: 8086
    environment:
      INFLUXDB_DB: sensordata
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: telegraf
    volumes:
      - /home/ubuntu/PI4Server/mqtt_microservices/influxdb/db:/var/lib/influxdb
      - /home/ubuntu/PI4Server/mqtt_microservices/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
