version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - target: 1883
        published: 1883
        mode: host
      - target: 9001
        published: 9001
        mode: host
    volumes:
      - mqttconf:/mosquitto/config/mosquitto.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`mqtt.localhost`)"

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongodbdata:/data/db
    ports:
      - target: 27017
        published: 27017
        mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: defaultpassword
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`mongo.localhost`)"

  telegraf:
    image: telegraf
    volumes:
      - telegrafdata:/etc/telegraf

  chronograf:
    image: chronograf:1.8
    ports:
      - target: 8888
        published: 8888
        mode: host
    volumes:
      - chronografvolume:/var/lib/chronograf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`chronograf.localhost`)"
        - "traefik.port=8888"
        - "traefik.backend=mqtt.chronograf"
        - "traefik.frontend.rule=Host:chronograf.mastern.net"

  influx:
    image: influxdb
    ports:
      - target: 8086
        published: 8086
        mode: host
    environment:
      INFLUXDB_DB: sensordata
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: telegraf
    volumes:
      - mqttinfluxdb:/var/lib/influxdb
      - mqttinfluxconf:/etc/influxdb/influxdb.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`influx.localhost`)"

volumes:
  chronografvolume:
    external: true
  mqttconf:
    external: true
  mongodbdata:
    external: true
  telegrafdata:
    external: true
  mqttinfluxdb:
    external: true
  mqttinfluxconf:
    external: true
