version: '3.8'
services:
  image: kapacitor:1.5-alpine
  volumes:
    - kapacitordatavolume:/var/lib/kapacitor
    - kapacitortickvolume:/home/kapacitor
    - /root/configs/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
  environment:
    KAPACITOR_INFLUXDB_0_URLS_0: http://influx:8086
  labels:
    - "traefik.backend=kapacitorbackend"
    - "traefik.enable=true"
    - "traefik.port=9092"
  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - target: 1883
        published: 1883
      - target: 9001
        published: 9001
    volumes:
      - mqttconf:/mosquitto/config
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      placement:
        constraints:
          - node.role == manager
      labels:
        - tiny.angry.kitten.autodeploy

  mongodb:
    image: mongo:4.4.1-bionic
    volumes:
      - mongodbdata:/data/db
    ports:
      - target: 27017
        published: 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: defaultpassword
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`mongo.localhost`)"

  telegraf:
    image: telegraf:1.16
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegrafconfig
        target: /etc/telegraf/telegraf.conf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
      placement:
        constraints:
          - node.role == manager

  chronograf:
    image: chronograf:1.8
    ports:
      - target: 8888
        published: 8888
    volumes:
      - chronografvolume:/var/lib/chronograf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefixStrip:/chronograf"
        - "traefik.http.routers.api.rule=Host(`chronograf.localhost`)"
        - "traefik.port=8888"
        - "traefik.backend=mqtt.chronograf"
        - traefik.http.services.chronograf.loadbalancer.server.port=8888
        - tiny.angry.kitten.autodeploy

  influx:
    image: influxdb:1.7
    ports:
      - target: 8086
        published: 8086
    environment:
      INFLUXDB_DB: sensordata
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: telegraf
    volumes:
      - mqttinfluxdb:/var/lib/influxdb
      - mqttinfluxconf:/etc/influxdb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`influx.localhost`)"

volumes:
  chronografvolume:
    external: true
  mqttconf:
    external: true
  mongodbdata:
    external: true
  telegrafdata:
    external: true
  mqttinfluxdb:
    external: true
  mqttinfluxconf:
    external: true
  kapacitorvolume:
    external: true
  kapacitortickvolume:
    external: true

configs:
  telegrafconfig:
    file: telegraf/telegraf.conf
  kapacitorconfig:
    file: kapacitor/kapacitor.conf
