version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - target: 1883
        published: 1883
        mode: host
      - target: 9001
        published: 9001
        mode: host
    volumes:
      - /home/ubuntu/PI4Server/mqtt_microservices/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongodb:
    image: mongo
    restart: always
    volumes:
      - /home/ubuntu/PI4Server/mqtt_microservices/mongodb:/data/db
    ports:
      target: 27017
      published: 27017
      mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: defaultpassword

  telegraf:
    image: telegraf
    volumes:
      - /home/ubuntu/PI4Server/mqtt_microservices/telegraf/:/etc/telegraf

  influx:
    image: influxdb
    ports:
      - target: 8086
        published: 8086
        mode: host
    environment:
      INFLUXDB_DB: sensordata
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: telegraf
    volumes:
      - /home/ubuntu/PI4Server/mqtt_microservices/influxdb/db:/var/lib/influxdb
      - /home/ubuntu/PI4Server/mqtt_microservices/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
