version: '3.8'
services:
  league_notifications:
    image: tinyangrykitten/livegamenotification
    deploy:
      labels:
        - tiny.angry.kitten.autodeploy
  wakeonlan:
    image: tinyangrykitten/wakeonlan
    networks:
      - host
    deploy:
      labels:
        - tiny.angry.kitten.autodeploy
  hueserver:
    image: tinyangrykitten/hueserver
    networks:
      - host
    deploy:
      labels:
        - tiny.angry.kitten.autodeploy
  notifications:
    image: tinyangrykitten/notifications
    networks:
      - host
    deploy:
      labels:
        - tiny.angry.kitten.autodeploy
  harmonyhub:
    image: tinyangrykitten/harmonyhub-server
    networks:
      - host
    deploy:
      labels:
        - tiny.angry.kitten.autodeploy
networks:
  host:
    external: true
