version: '3.8'
services:
  homey_client:
    image: tinyangrykitten/homeyclient
    ports:
      - published: 8881
        target: 8881
    environment:
      - httpPort=8881
    logging:
      driver: "splunk"
      options:
        splunk-token: 4189e578-d38c-482b-a7d4-40cefa1760c4
        splunk-url: https://192.168.50.3:8088
        splunk-format: json
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy

  league_notifications:
    image: tinyangrykitten/livegamenotification
    logging:
      driver: "splunk"
      options:
        splunk-token: 4189e578-d38c-482b-a7d4-40cefa1760c4
        splunk-url: https://192.168.50.3:8088
        splunk-format: json
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  wakeonlan:
    image: tinyangrykitten/wakeonlan
    logging:
      driver: "splunk"
      options:
        splunk-token: 4189e578-d38c-482b-a7d4-40cefa1760c4
        splunk-url: https://192.168.50.3:8088
        splunk-format: json
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  hueserver:
    image: tinyangrykitten/hueserver
    logging:
      driver: "splunk"
      options:
        splunk-token: 4189e578-d38c-482b-a7d4-40cefa1760c4
        splunk-url: https://192.168.50.3:8088
        splunk-format: json
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  notifications:
    image: tinyangrykitten/notifications
    logging:
      driver: "splunk"
      options:
        splunk-token: 4189e578-d38c-482b-a7d4-40cefa1760c4
        splunk-url: https://192.168.50.3:8088
        splunk-format: json
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  harmonyhub:
    image: tinyangrykitten/harmonyhub-server
    logging:
      driver: "splunk"
      options:
        splunk-token: 4189e578-d38c-482b-a7d4-40cefa1760c4
        splunk-url: https://192.168.50.3:8088
        splunk-format: json
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
networks:
  host:
    external: true
