version: '3.8'
services:
  league_notifications:
    image: tinyangrykitten/livegamenotification
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  wakeonlan:
    image: tinyangrykitten/wakeonlan
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  hueserver:
    image: tinyangrykitten/hueserver
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  notifications:
    image: tinyangrykitten/notifications
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
  harmonyhub:
    image: tinyangrykitten/harmonyhub-server
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    networks:
      - host
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 300s
      labels:
        - tiny.angry.kitten.autodeploy
networks:
  host:
    external: true
